version: "3.8"

services:
  resume-backend:
    build: .
    container_name: resume-backend
    restart: always
    env_file:
      - .env
    ports:
      - "9008:9008"

    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 1024M
